apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: url-shortener
spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "url-shortener"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/url-shortener"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/url-shortener" -}}
          DB_USER={{ .Data.data.DB_USER }}
          DB_PASSWORD={{ .Data.data.DB_PASSWORD }}
          DB_NAME={{ .Data.data.DB_NAME }}
          {{- end }}

    spec:
      serviceAccountName: backend
      containers:
        - name: backend
          image: shaharyarshakir/url-shortener-backend:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: app-config
            # Secrets are loaded dynamically via Vault agent sidecar
            # - secretRef:
            #     name: app-secret

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /livez
              port: 8080

            initialDelaySeconds: 10
            periodSeconds: 15

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi
