// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attendance struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	UserID    pgtype.UUID
	Duration  int32
}

type LiveSession struct {
	ID           pgtype.UUID
	CourseID     pgtype.UUID
	InstructorID pgtype.UUID
	Title        string
	Description  pgtype.Text
	ScheduledAt  pgtype.Timestamp
	StartedAt    pgtype.Timestamp
	EndedAt      pgtype.Timestamp
	Status       string
	CreatedAt    pgtype.Timestamp
}

type OutboxEvent struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	AggregateType string
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamp
	PublishedAt   pgtype.Timestamp
}

type Participant struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	JoinedAt  pgtype.Timestamp
	LeftAt    pgtype.Timestamp
}
