// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLiveSession = `-- name: CreateLiveSession :one
INSERT INTO live_sessions (id, course_id, instructor_id, title, description, scheduled_at, started_at, ended_at, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, course_id, instructor_id, title, description, scheduled_at, started_at, ended_at, status, created_at
`

type CreateLiveSessionParams struct {
	ID           pgtype.UUID
	CourseID     pgtype.UUID
	InstructorID pgtype.UUID
	Title        string
	Description  pgtype.Text
	ScheduledAt  pgtype.Timestamp
	StartedAt    pgtype.Timestamp
	EndedAt      pgtype.Timestamp
	Status       string
	CreatedAt    pgtype.Timestamp
}

func (q *Queries) CreateLiveSession(ctx context.Context, arg CreateLiveSessionParams) (LiveSession, error) {
	row := q.db.QueryRow(ctx, createLiveSession,
		arg.ID,
		arg.CourseID,
		arg.InstructorID,
		arg.Title,
		arg.Description,
		arg.ScheduledAt,
		arg.StartedAt,
		arg.EndedAt,
		arg.Status,
		arg.CreatedAt,
	)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.InstructorID,
		&i.Title,
		&i.Description,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO participants (id, session_id, user_id, role, joined_at, left_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_id, user_id, role, joined_at, left_at
`

type CreateParticipantParams struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	JoinedAt  pgtype.Timestamp
	LeftAt    pgtype.Timestamp
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.ID,
		arg.SessionID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
		arg.LeftAt,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const deleteLiveSession = `-- name: DeleteLiveSession :exec
DELETE FROM live_sessions WHERE id = $1
`

func (q *Queries) DeleteLiveSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLiveSession, id)
	return err
}

const getAttendance = `-- name: GetAttendance :one
SELECT id, session_id, user_id, duration FROM attendance WHERE session_id = $1 AND user_id = $2
`

type GetAttendanceParams struct {
	SessionID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) GetAttendance(ctx context.Context, arg GetAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, getAttendance, arg.SessionID, arg.UserID)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Duration,
	)
	return i, err
}

const getLiveSessionByID = `-- name: GetLiveSessionByID :one
SELECT id, course_id, instructor_id, title, description, scheduled_at, started_at, ended_at, status, created_at FROM live_sessions WHERE id = $1
`

func (q *Queries) GetLiveSessionByID(ctx context.Context, id pgtype.UUID) (LiveSession, error) {
	row := q.db.QueryRow(ctx, getLiveSessionByID, id)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.InstructorID,
		&i.Title,
		&i.Description,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, session_id, user_id, role, joined_at, left_at FROM participants
WHERE session_id = $1 AND user_id = $2
ORDER BY joined_at DESC
LIMIT 1
`

type GetParticipantParams struct {
	SessionID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) GetParticipant(ctx context.Context, arg GetParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipant, arg.SessionID, arg.UserID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (id, aggregate_id, aggregate_type, event_type, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOutboxEventParams struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	AggregateType string
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamp
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.AggregateID,
		arg.AggregateType,
		arg.EventType,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const listAttendanceBySession = `-- name: ListAttendanceBySession :many
SELECT id, session_id, user_id, duration FROM attendance WHERE session_id = $1
`

func (q *Queries) ListAttendanceBySession(ctx context.Context, sessionID pgtype.UUID) ([]Attendance, error) {
	rows, err := q.db.Query(ctx, listAttendanceBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendance
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSessionsByCourse = `-- name: ListLiveSessionsByCourse :many
SELECT id, course_id, instructor_id, title, description, scheduled_at, started_at, ended_at, status, created_at FROM live_sessions WHERE course_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListLiveSessionsByCourse(ctx context.Context, courseID pgtype.UUID) ([]LiveSession, error) {
	rows, err := q.db.Query(ctx, listLiveSessionsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiveSession
	for rows.Next() {
		var i LiveSession
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.InstructorID,
			&i.Title,
			&i.Description,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedOutboxEvents = `-- name: ListUnpublishedOutboxEvents :many
SELECT id, aggregate_id, aggregate_type, event_type, payload, created_at, published_at FROM outbox_events
WHERE published_at IS NULL
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventAsPublished = `-- name: MarkOutboxEventAsPublished :exec
UPDATE outbox_events
SET published_at = $2
WHERE id = $1
`

type MarkOutboxEventAsPublishedParams struct {
	ID          pgtype.UUID
	PublishedAt pgtype.Timestamp
}

func (q *Queries) MarkOutboxEventAsPublished(ctx context.Context, arg MarkOutboxEventAsPublishedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventAsPublished, arg.ID, arg.PublishedAt)
	return err
}

const updateLiveSessionDetails = `-- name: UpdateLiveSessionDetails :one
UPDATE live_sessions
SET title = $2, description = $3, scheduled_at = $4
WHERE id = $1
RETURNING id, course_id, instructor_id, title, description, scheduled_at, started_at, ended_at, status, created_at
`

type UpdateLiveSessionDetailsParams struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	ScheduledAt pgtype.Timestamp
}

func (q *Queries) UpdateLiveSessionDetails(ctx context.Context, arg UpdateLiveSessionDetailsParams) (LiveSession, error) {
	row := q.db.QueryRow(ctx, updateLiveSessionDetails,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ScheduledAt,
	)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.InstructorID,
		&i.Title,
		&i.Description,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateLiveSessionStatus = `-- name: UpdateLiveSessionStatus :one
UPDATE live_sessions
SET status = $2, started_at = $3, ended_at = $4
WHERE id = $1
RETURNING id, course_id, instructor_id, title, description, scheduled_at, started_at, ended_at, status, created_at
`

type UpdateLiveSessionStatusParams struct {
	ID        pgtype.UUID
	Status    string
	StartedAt pgtype.Timestamp
	EndedAt   pgtype.Timestamp
}

func (q *Queries) UpdateLiveSessionStatus(ctx context.Context, arg UpdateLiveSessionStatusParams) (LiveSession, error) {
	row := q.db.QueryRow(ctx, updateLiveSessionStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.InstructorID,
		&i.Title,
		&i.Description,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateParticipantLeft = `-- name: UpdateParticipantLeft :one
UPDATE participants
SET left_at = $3
WHERE session_id = $1 AND user_id = $2 AND left_at IS NULL
RETURNING id, session_id, user_id, role, joined_at, left_at
`

type UpdateParticipantLeftParams struct {
	SessionID pgtype.UUID
	UserID    pgtype.UUID
	LeftAt    pgtype.Timestamp
}

func (q *Queries) UpdateParticipantLeft(ctx context.Context, arg UpdateParticipantLeftParams) (Participant, error) {
	row := q.db.QueryRow(ctx, updateParticipantLeft, arg.SessionID, arg.UserID, arg.LeftAt)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const upsertAttendance = `-- name: UpsertAttendance :one
INSERT INTO attendance (id, session_id, user_id, duration)
VALUES ($1, $2, $3, $4)
ON CONFLICT (session_id, user_id)
DO UPDATE SET duration = attendance.duration + EXCLUDED.duration
RETURNING id, session_id, user_id, duration
`

type UpsertAttendanceParams struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	UserID    pgtype.UUID
	Duration  int32
}

func (q *Queries) UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, upsertAttendance,
		arg.ID,
		arg.SessionID,
		arg.UserID,
		arg.Duration,
	)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Duration,
	)
	return i, err
}
