apiVersion: v1
kind: Service
metadata:
  name: {{ include "indexer.fullname" . }}
  labels:
    app: {{ include "indexer.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    app: {{ include "indexer.name" . }}
