import {
  ExceptionFilter,
  Catch,
  ArgumentsHost,
  HttpException,
  HttpStatus,
} from '@nestjs/common';
import { Response } from 'express';
import { v4 as uuidv4 } from 'uuid';

@Catch()
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: any, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<any>();

    const status =
      exception instanceof HttpException
        ? exception.getStatus()
        : HttpStatus.INTERNAL_SERVER_ERROR;

    const exceptionResponse =
      exception instanceof HttpException
        ? exception.getResponse()
        : null;

    let message = 'Internal server error';
    let code = 'INTERNAL_SERVER_ERROR';

    if (exceptionResponse) {
      if (typeof exceptionResponse === 'string') {
        message = exceptionResponse;
      } else if (typeof exceptionResponse === 'object') {
        const resObj = exceptionResponse as any;
        message = Array.isArray(resObj.message)
          ? resObj.message.join(', ')
          : resObj.message || message;
        code = resObj.error || code;
      }
    } else if (exception && exception.message) {
      message = exception.message;
    }

    // Convert standard Nest validation/HTTP names to uppercase snake-case codes
    code = code.toUpperCase().replace(/\s+/g, '_');

    // Extract requestId generated by logging middleware or create a fallback
    const requestId = request.id || request.headers?.['x-request-id'] || uuidv4();

    response.status(status).json({
      success: false,
      error: {
        code,
        message,
      },
      requestId,
    });
  }
}
