# Generated by Django 5.2.16 on 2026-07-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFileORM',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('filename', models.TextField()),
                ('mime_type', models.TextField()),
                ('size', models.BigIntegerField()),
                ('storage_key', models.TextField(unique=True)),
                ('status', models.TextField()),
                ('checksum', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'media_files',
                'indexes': [models.Index(fields=['owner_id'], name='media_files_owner_i_2ea9c2_idx'), models.Index(fields=['status'], name='media_files_status_3802c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadSessionORM',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('media_id', models.UUIDField()),
                ('upload_id', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'upload_sessions',
                'indexes': [models.Index(fields=['media_id'], name='upload_sess_media_i_9e808c_idx')],
            },
        ),
    ]
