# Generated by Django 5.2.16 on 2026-07-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsessionorm',
            name='part_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadsessionorm',
            name='total_parts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadsessionorm',
            name='uploaded_parts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='uploadsessionorm',
            index=models.Index(fields=['expires_at'], name='upload_sess_expires_aebd1e_idx'),
        ),
    ]
