name: Build Website
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t html-web-app ./html-web-app

      - name: Verify Files
        run: |
          ls -la ./html-web-app
