apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "url-shortener.fullname" . }}-backend
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
