// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChunk = `-- name: CreateChunk :one


INSERT INTO chunks
(
document_id,
content
)

VALUES
(
$1,
$2
)

RETURNING id, document_id, content, embedding, created_at
`

type CreateChunkParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	Content    string    `json:"content"`
}

func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) (Chunk, error) {
	row := q.db.QueryRow(ctx, createChunk, arg.DocumentID, arg.Content)
	var i Chunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const getChunks = `-- name: GetChunks :many


SELECT id, document_id, content, embedding, created_at

FROM chunks

WHERE document_id=$1
`

func (q *Queries) GetChunks(ctx context.Context, documentID uuid.UUID) ([]Chunk, error) {
	rows, err := q.db.Query(ctx, getChunks, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chunk
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Content,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
