// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChunk = `-- name: CreateChunk :one

INSERT INTO chunks (
    document_id,
    content
)
VALUES ($1, $2)
RETURNING id, document_id, content, created_at
`

type CreateChunkParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	Content    string    `json:"content"`
}

type CreateChunkRow struct {
	ID         uuid.UUID        `json:"id"`
	DocumentID uuid.UUID        `json:"document_id"`
	Content    string           `json:"content"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) (CreateChunkRow, error) {
	row := q.db.QueryRow(ctx, createChunk, arg.DocumentID, arg.Content)
	var i CreateChunkRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getChunks = `-- name: GetChunks :many

SELECT id, document_id, content, created_at
FROM chunks
WHERE document_id = $1
`

type GetChunksRow struct {
	ID         uuid.UUID        `json:"id"`
	DocumentID uuid.UUID        `json:"document_id"`
	Content    string           `json:"content"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetChunks(ctx context.Context, documentID uuid.UUID) ([]GetChunksRow, error) {
	rows, err := q.db.Query(ctx, getChunks, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChunksRow
	for rows.Next() {
		var i GetChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
