// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one

INSERT INTO documents
(
title,
filename,
content_type
)

VALUES
(
$1,
$2,
$3
)

RETURNING id, title, filename, content_type, created_at
`

type CreateDocumentParams struct {
	Title       string      `json:"title"`
	Filename    string      `json:"filename"`
	ContentType pgtype.Text `json:"content_type"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument, arg.Title, arg.Filename, arg.ContentType)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Filename,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one

SELECT id, title, filename, content_type, created_at

FROM documents

WHERE id=$1
`

func (q *Queries) GetDocument(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Filename,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const getDocuments = `-- name: GetDocuments :many

SELECT id, title, filename, content_type, created_at

FROM documents

ORDER BY created_at DESC
`

func (q *Queries) GetDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
