// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Chunk struct {
	ID         uuid.UUID        `json:"id"`
	DocumentID uuid.UUID        `json:"document_id"`
	Content    string           `json:"content"`
	Embedding  pgvector.Vector  `json:"embedding"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Document struct {
	ID          uuid.UUID        `json:"id"`
	Title       string           `json:"title"`
	Filename    string           `json:"filename"`
	ContentType pgtype.Text      `json:"content_type"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
