// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

const searchChunks = `-- name: SearchChunks :many

SELECT 
    id,
    document_id,
    content
FROM chunks
ORDER BY embedding <=> $1
LIMIT $2
`

type SearchChunksParams struct {
	Embedding pgvector.Vector `json:"embedding"`
	Limit     int32           `json:"limit"`
}

type SearchChunksRow struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	Content    string    `json:"content"`
}

func (q *Queries) SearchChunks(ctx context.Context, arg SearchChunksParams) ([]SearchChunksRow, error) {
	rows, err := q.db.Query(ctx, searchChunks, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchChunksRow
	for rows.Next() {
		var i SearchChunksRow
		if err := rows.Scan(&i.ID, &i.DocumentID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
