// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type CodingProblem struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Slug          string         `json:"slug"`
	Difficulty    string         `json:"difficulty"`
	Statement     string         `json:"statement"`
	Constraints   sql.NullString `json:"constraints"`
	TimeLimitMs   int32          `json:"time_limit_ms"`
	MemoryLimitMb int32          `json:"memory_limit_mb"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Outbox struct {
	ID            uuid.UUID       `json:"id"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	AggregateType string          `json:"aggregate_type"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	CreatedAt     time.Time       `json:"created_at"`
	ProcessedAt   sql.NullTime    `json:"processed_at"`
}

type ProblemLanguage struct {
	ProblemID   uuid.UUID      `json:"problem_id"`
	Language    string         `json:"language"`
	StarterCode sql.NullString `json:"starter_code"`
}

type Submission struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.UUID     `json:"user_id"`
	ProblemID uuid.UUID     `json:"problem_id"`
	Language  string        `json:"language"`
	Status    string        `json:"status"`
	Score     sql.NullInt32 `json:"score"`
	Runtime   sql.NullInt64 `json:"runtime"`
	Memory    sql.NullInt64 `json:"memory"`
	Code      string        `json:"code"`
	CreatedAt time.Time     `json:"created_at"`
}

type SubmissionResult struct {
	SubmissionID uuid.UUID      `json:"submission_id"`
	TestCaseID   uuid.UUID      `json:"test_case_id"`
	Runtime      sql.NullInt64  `json:"runtime"`
	Memory       sql.NullInt64  `json:"memory"`
	Status       string         `json:"status"`
	Stdout       sql.NullString `json:"stdout"`
	Stderr       sql.NullString `json:"stderr"`
	CreatedAt    time.Time      `json:"created_at"`
}

type TestCase struct {
	ID             uuid.UUID      `json:"id"`
	ProblemID      uuid.UUID      `json:"problem_id"`
	Input          sql.NullString `json:"input"`
	ExpectedOutput sql.NullString `json:"expected_output"`
	Hidden         bool           `json:"hidden"`
	Weight         int32          `json:"weight"`
	CreatedAt      time.Time      `json:"created_at"`
}
