// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox (aggregate_id, aggregate_type, event_type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, aggregate_id, aggregate_type, event_type, payload, created_at, processed_at
`

type CreateOutboxEventParams struct {
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	AggregateType string          `json:"aggregate_type"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRowContext(ctx, createOutboxEvent,
		arg.AggregateID,
		arg.AggregateType,
		arg.EventType,
		arg.Payload,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const createProblem = `-- name: CreateProblem :one
INSERT INTO coding_problems (title, slug, difficulty, statement, constraints, time_limit_ms, memory_limit_mb)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, slug, difficulty, statement, constraints, time_limit_ms, memory_limit_mb, created_at
`

type CreateProblemParams struct {
	Title         string         `json:"title"`
	Slug          string         `json:"slug"`
	Difficulty    string         `json:"difficulty"`
	Statement     string         `json:"statement"`
	Constraints   sql.NullString `json:"constraints"`
	TimeLimitMs   int32          `json:"time_limit_ms"`
	MemoryLimitMb int32          `json:"memory_limit_mb"`
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (CodingProblem, error) {
	row := q.db.QueryRowContext(ctx, createProblem,
		arg.Title,
		arg.Slug,
		arg.Difficulty,
		arg.Statement,
		arg.Constraints,
		arg.TimeLimitMs,
		arg.MemoryLimitMb,
	)
	var i CodingProblem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Difficulty,
		&i.Statement,
		&i.Constraints,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.CreatedAt,
	)
	return i, err
}

const createProblemLanguage = `-- name: CreateProblemLanguage :one
INSERT INTO problem_languages (problem_id, language, starter_code)
VALUES ($1, $2, $3)
RETURNING problem_id, language, starter_code
`

type CreateProblemLanguageParams struct {
	ProblemID   uuid.UUID      `json:"problem_id"`
	Language    string         `json:"language"`
	StarterCode sql.NullString `json:"starter_code"`
}

func (q *Queries) CreateProblemLanguage(ctx context.Context, arg CreateProblemLanguageParams) (ProblemLanguage, error) {
	row := q.db.QueryRowContext(ctx, createProblemLanguage, arg.ProblemID, arg.Language, arg.StarterCode)
	var i ProblemLanguage
	err := row.Scan(&i.ProblemID, &i.Language, &i.StarterCode)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (user_id, problem_id, language, code)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, problem_id, language, status, score, runtime, memory, code, created_at
`

type CreateSubmissionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProblemID uuid.UUID `json:"problem_id"`
	Language  string    `json:"language"`
	Code      string    `json:"code"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRowContext(ctx, createSubmission,
		arg.UserID,
		arg.ProblemID,
		arg.Language,
		arg.Code,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.Language,
		&i.Status,
		&i.Score,
		&i.Runtime,
		&i.Memory,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const createSubmissionResult = `-- name: CreateSubmissionResult :one
INSERT INTO submission_results (submission_id, test_case_id, runtime, memory, status, stdout, stderr)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING submission_id, test_case_id, runtime, memory, status, stdout, stderr, created_at
`

type CreateSubmissionResultParams struct {
	SubmissionID uuid.UUID      `json:"submission_id"`
	TestCaseID   uuid.UUID      `json:"test_case_id"`
	Runtime      sql.NullInt64  `json:"runtime"`
	Memory       sql.NullInt64  `json:"memory"`
	Status       string         `json:"status"`
	Stdout       sql.NullString `json:"stdout"`
	Stderr       sql.NullString `json:"stderr"`
}

func (q *Queries) CreateSubmissionResult(ctx context.Context, arg CreateSubmissionResultParams) (SubmissionResult, error) {
	row := q.db.QueryRowContext(ctx, createSubmissionResult,
		arg.SubmissionID,
		arg.TestCaseID,
		arg.Runtime,
		arg.Memory,
		arg.Status,
		arg.Stdout,
		arg.Stderr,
	)
	var i SubmissionResult
	err := row.Scan(
		&i.SubmissionID,
		&i.TestCaseID,
		&i.Runtime,
		&i.Memory,
		&i.Status,
		&i.Stdout,
		&i.Stderr,
		&i.CreatedAt,
	)
	return i, err
}

const createTestCase = `-- name: CreateTestCase :one
INSERT INTO test_cases (problem_id, input, expected_output, hidden, weight)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, problem_id, input, expected_output, hidden, weight, created_at
`

type CreateTestCaseParams struct {
	ProblemID      uuid.UUID      `json:"problem_id"`
	Input          sql.NullString `json:"input"`
	ExpectedOutput sql.NullString `json:"expected_output"`
	Hidden         bool           `json:"hidden"`
	Weight         int32          `json:"weight"`
}

func (q *Queries) CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRowContext(ctx, createTestCase,
		arg.ProblemID,
		arg.Input,
		arg.ExpectedOutput,
		arg.Hidden,
		arg.Weight,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Input,
		&i.ExpectedOutput,
		&i.Hidden,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProblem = `-- name: DeleteProblem :exec
DELETE FROM coding_problems WHERE id = $1
`

func (q *Queries) DeleteProblem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProblem, id)
	return err
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, title, slug, difficulty, statement, constraints, time_limit_ms, memory_limit_mb, created_at FROM coding_problems WHERE id = $1
`

func (q *Queries) GetProblemByID(ctx context.Context, id uuid.UUID) (CodingProblem, error) {
	row := q.db.QueryRowContext(ctx, getProblemByID, id)
	var i CodingProblem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Difficulty,
		&i.Statement,
		&i.Constraints,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.CreatedAt,
	)
	return i, err
}

const getProblemBySlug = `-- name: GetProblemBySlug :one
SELECT id, title, slug, difficulty, statement, constraints, time_limit_ms, memory_limit_mb, created_at FROM coding_problems WHERE slug = $1
`

func (q *Queries) GetProblemBySlug(ctx context.Context, slug string) (CodingProblem, error) {
	row := q.db.QueryRowContext(ctx, getProblemBySlug, slug)
	var i CodingProblem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Difficulty,
		&i.Statement,
		&i.Constraints,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.CreatedAt,
	)
	return i, err
}

const getProblemLanguages = `-- name: GetProblemLanguages :many
SELECT problem_id, language, starter_code FROM problem_languages WHERE problem_id = $1
`

func (q *Queries) GetProblemLanguages(ctx context.Context, problemID uuid.UUID) ([]ProblemLanguage, error) {
	rows, err := q.db.QueryContext(ctx, getProblemLanguages, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProblemLanguage{}
	for rows.Next() {
		var i ProblemLanguage
		if err := rows.Scan(&i.ProblemID, &i.Language, &i.StarterCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, user_id, problem_id, language, status, score, runtime, memory, code, created_at FROM submissions WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.Language,
		&i.Status,
		&i.Score,
		&i.Runtime,
		&i.Memory,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmissionResults = `-- name: GetSubmissionResults :many
SELECT submission_id, test_case_id, runtime, memory, status, stdout, stderr, created_at FROM submission_results WHERE submission_id = $1
`

func (q *Queries) GetSubmissionResults(ctx context.Context, submissionID uuid.UUID) ([]SubmissionResult, error) {
	rows, err := q.db.QueryContext(ctx, getSubmissionResults, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubmissionResult{}
	for rows.Next() {
		var i SubmissionResult
		if err := rows.Scan(
			&i.SubmissionID,
			&i.TestCaseID,
			&i.Runtime,
			&i.Memory,
			&i.Status,
			&i.Stdout,
			&i.Stderr,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestCasesByProblemID = `-- name: GetTestCasesByProblemID :many
SELECT id, problem_id, input, expected_output, hidden, weight, created_at FROM test_cases WHERE problem_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetTestCasesByProblemID(ctx context.Context, problemID uuid.UUID) ([]TestCase, error) {
	rows, err := q.db.QueryContext(ctx, getTestCasesByProblemID, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Input,
			&i.ExpectedOutput,
			&i.Hidden,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT id, aggregate_id, aggregate_type, event_type, payload, created_at, processed_at FROM outbox WHERE processed_at IS NULL ORDER BY created_at ASC LIMIT 100
`

func (q *Queries) ListPendingOutboxEvents(ctx context.Context) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, listPendingOutboxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblems = `-- name: ListProblems :many
SELECT id, title, slug, difficulty, statement, constraints, time_limit_ms, memory_limit_mb, created_at FROM coding_problems ORDER BY created_at DESC
`

func (q *Queries) ListProblems(ctx context.Context) ([]CodingProblem, error) {
	rows, err := q.db.QueryContext(ctx, listProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodingProblem{}
	for rows.Next() {
		var i CodingProblem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Difficulty,
			&i.Statement,
			&i.Constraints,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByProblem = `-- name: ListSubmissionsByProblem :many
SELECT id, user_id, problem_id, language, status, score, runtime, memory, code, created_at FROM submissions WHERE problem_id = $1 ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListSubmissionsByProblem(ctx context.Context, problemID uuid.UUID) ([]Submission, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissionsByProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.Language,
			&i.Status,
			&i.Score,
			&i.Runtime,
			&i.Memory,
			&i.Code,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByUser = `-- name: ListSubmissionsByUser :many
SELECT id, user_id, problem_id, language, status, score, runtime, memory, code, created_at FROM submissions WHERE user_id = $1 ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListSubmissionsByUser(ctx context.Context, userID uuid.UUID) ([]Submission, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.Language,
			&i.Status,
			&i.Score,
			&i.Runtime,
			&i.Memory,
			&i.Code,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventAsProcessed = `-- name: MarkOutboxEventAsProcessed :exec
UPDATE outbox SET processed_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOutboxEventAsProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markOutboxEventAsProcessed, id)
	return err
}

const updateProblem = `-- name: UpdateProblem :one
UPDATE coding_problems
SET title = $2, difficulty = $3, statement = $4, constraints = $5, time_limit_ms = $6, memory_limit_mb = $7
WHERE id = $1
RETURNING id, title, slug, difficulty, statement, constraints, time_limit_ms, memory_limit_mb, created_at
`

type UpdateProblemParams struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Difficulty    string         `json:"difficulty"`
	Statement     string         `json:"statement"`
	Constraints   sql.NullString `json:"constraints"`
	TimeLimitMs   int32          `json:"time_limit_ms"`
	MemoryLimitMb int32          `json:"memory_limit_mb"`
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) (CodingProblem, error) {
	row := q.db.QueryRowContext(ctx, updateProblem,
		arg.ID,
		arg.Title,
		arg.Difficulty,
		arg.Statement,
		arg.Constraints,
		arg.TimeLimitMs,
		arg.MemoryLimitMb,
	)
	var i CodingProblem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Difficulty,
		&i.Statement,
		&i.Constraints,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.CreatedAt,
	)
	return i, err
}

const updateSubmission = `-- name: UpdateSubmission :one
UPDATE submissions
SET status = $2, score = $3, runtime = $4, memory = $5
WHERE id = $1
RETURNING id, user_id, problem_id, language, status, score, runtime, memory, code, created_at
`

type UpdateSubmissionParams struct {
	ID      uuid.UUID     `json:"id"`
	Status  string        `json:"status"`
	Score   sql.NullInt32 `json:"score"`
	Runtime sql.NullInt64 `json:"runtime"`
	Memory  sql.NullInt64 `json:"memory"`
}

func (q *Queries) UpdateSubmission(ctx context.Context, arg UpdateSubmissionParams) (Submission, error) {
	row := q.db.QueryRowContext(ctx, updateSubmission,
		arg.ID,
		arg.Status,
		arg.Score,
		arg.Runtime,
		arg.Memory,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.Language,
		&i.Status,
		&i.Score,
		&i.Runtime,
		&i.Memory,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}
