// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error)
	CreateProblem(ctx context.Context, arg CreateProblemParams) (CodingProblem, error)
	CreateProblemLanguage(ctx context.Context, arg CreateProblemLanguageParams) (ProblemLanguage, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateSubmissionResult(ctx context.Context, arg CreateSubmissionResultParams) (SubmissionResult, error)
	CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error)
	DeleteProblem(ctx context.Context, id uuid.UUID) error
	GetProblemByID(ctx context.Context, id uuid.UUID) (CodingProblem, error)
	GetProblemBySlug(ctx context.Context, slug string) (CodingProblem, error)
	GetProblemLanguages(ctx context.Context, problemID uuid.UUID) ([]ProblemLanguage, error)
	GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error)
	GetSubmissionResults(ctx context.Context, submissionID uuid.UUID) ([]SubmissionResult, error)
	GetTestCasesByProblemID(ctx context.Context, problemID uuid.UUID) ([]TestCase, error)
	ListPendingOutboxEvents(ctx context.Context) ([]Outbox, error)
	ListProblems(ctx context.Context) ([]CodingProblem, error)
	ListSubmissionsByProblem(ctx context.Context, problemID uuid.UUID) ([]Submission, error)
	ListSubmissionsByUser(ctx context.Context, userID uuid.UUID) ([]Submission, error)
	MarkOutboxEventAsProcessed(ctx context.Context, id uuid.UUID) error
	UpdateProblem(ctx context.Context, arg UpdateProblemParams) (CodingProblem, error)
	UpdateSubmission(ctx context.Context, arg UpdateSubmissionParams) (Submission, error)
}

var _ Querier = (*Queries)(nil)
