// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   pgtype.UUID
	Name string
}

type Course struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	Title        string
	Slug         string
	Subtitle     pgtype.Text
	Description  pgtype.Text
	Level        pgtype.Text
	Language     pgtype.Text
	Price        pgtype.Numeric
	ThumbnailUrl pgtype.Text
	Status       string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type CourseCategory struct {
	CourseID   pgtype.UUID
	CategoryID pgtype.UUID
}

type CourseObjective struct {
	ID        pgtype.UUID
	CourseID  pgtype.UUID
	Objective string
	Position  int32
}

type CourseRequirement struct {
	ID          pgtype.UUID
	CourseID    pgtype.UUID
	Requirement string
	Position    int32
}

type CourseTarget struct {
	ID       pgtype.UUID
	CourseID pgtype.UUID
	Target   string
	Position int32
}

type Enrollment struct {
	ID         pgtype.UUID
	CourseID   pgtype.UUID
	UserID     pgtype.UUID
	EnrolledAt pgtype.Timestamp
}

type InboxEvent struct {
	EventID     pgtype.UUID
	ProcessedAt pgtype.Timestamp
}

type Lesson struct {
	ID        pgtype.UUID
	SectionID pgtype.UUID
	Title     string
	Type      string
	Duration  pgtype.Int4
	Position  pgtype.Int4
}

type LessonOrder struct {
	SectionID  pgtype.UUID
	OrderedIds []pgtype.UUID
}

type LessonResource struct {
	ID        pgtype.UUID
	LessonID  pgtype.UUID
	Title     string
	Url       string
	Type      string
	CreatedAt pgtype.Timestamp
}

type OutboxEvent struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	AggregateType pgtype.Text
	EventType     pgtype.Text
	Payload       []byte
	CreatedAt     pgtype.Timestamp
	PublishedAt   pgtype.Timestamp
}

type Section struct {
	ID       pgtype.UUID
	CourseID pgtype.UUID
	Title    string
	Position int32
}
