// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCourseCategory = `-- name: AddCourseCategory :exec
INSERT INTO course_categories (course_id, category_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddCourseCategoryParams struct {
	CourseID   pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) AddCourseCategory(ctx context.Context, arg AddCourseCategoryParams) error {
	_, err := q.db.Exec(ctx, addCourseCategory, arg.CourseID, arg.CategoryID)
	return err
}

const clearCourseCategories = `-- name: ClearCourseCategories :exec
DELETE FROM course_categories WHERE course_id = $1
`

func (q *Queries) ClearCourseCategories(ctx context.Context, courseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCourseCategories, courseID)
	return err
}

const clearObjectives = `-- name: ClearObjectives :exec
DELETE FROM course_objectives WHERE course_id = $1
`

func (q *Queries) ClearObjectives(ctx context.Context, courseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearObjectives, courseID)
	return err
}

const clearRequirements = `-- name: ClearRequirements :exec
DELETE FROM course_requirements WHERE course_id = $1
`

func (q *Queries) ClearRequirements(ctx context.Context, courseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearRequirements, courseID)
	return err
}

const clearTargets = `-- name: ClearTargets :exec
DELETE FROM course_targets WHERE course_id = $1
`

func (q *Queries) ClearTargets(ctx context.Context, courseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearTargets, courseID)
	return err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (id, owner_id, title, slug, subtitle, description, level, language, price, thumbnail_url, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, owner_id, title, slug, subtitle, description, level, language, price, thumbnail_url, status, created_at, updated_at
`

type CreateCourseParams struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	Title        string
	Slug         string
	Subtitle     pgtype.Text
	Description  pgtype.Text
	Level        pgtype.Text
	Language     pgtype.Text
	Price        pgtype.Numeric
	ThumbnailUrl pgtype.Text
	Status       string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Slug,
		arg.Subtitle,
		arg.Description,
		arg.Level,
		arg.Language,
		arg.Price,
		arg.ThumbnailUrl,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Slug,
		&i.Subtitle,
		&i.Description,
		&i.Level,
		&i.Language,
		&i.Price,
		&i.ThumbnailUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (id, course_id, user_id, enrolled_at)
VALUES ($1, $2, $3, $4)
RETURNING id, course_id, user_id, enrolled_at
`

type CreateEnrollmentParams struct {
	ID         pgtype.UUID
	CourseID   pgtype.UUID
	UserID     pgtype.UUID
	EnrolledAt pgtype.Timestamp
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.ID,
		arg.CourseID,
		arg.UserID,
		arg.EnrolledAt,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.EnrolledAt,
	)
	return i, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (id, section_id, title, type, duration, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, section_id, title, type, duration, position
`

type CreateLessonParams struct {
	ID        pgtype.UUID
	SectionID pgtype.UUID
	Title     string
	Type      string
	Duration  pgtype.Int4
	Position  pgtype.Int4
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.ID,
		arg.SectionID,
		arg.Title,
		arg.Type,
		arg.Duration,
		arg.Position,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Title,
		&i.Type,
		&i.Duration,
		&i.Position,
	)
	return i, err
}

const createLessonResource = `-- name: CreateLessonResource :one
INSERT INTO lesson_resources (id, lesson_id, title, url, type, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, lesson_id, title, url, type, created_at
`

type CreateLessonResourceParams struct {
	ID        pgtype.UUID
	LessonID  pgtype.UUID
	Title     string
	Url       string
	Type      string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CreateLessonResource(ctx context.Context, arg CreateLessonResourceParams) (LessonResource, error) {
	row := q.db.QueryRow(ctx, createLessonResource,
		arg.ID,
		arg.LessonID,
		arg.Title,
		arg.Url,
		arg.Type,
		arg.CreatedAt,
	)
	var i LessonResource
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.Title,
		&i.Url,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const createObjective = `-- name: CreateObjective :one
INSERT INTO course_objectives (id, course_id, objective, position)
VALUES ($1, $2, $3, $4)
RETURNING id, course_id, objective, position
`

type CreateObjectiveParams struct {
	ID        pgtype.UUID
	CourseID  pgtype.UUID
	Objective string
	Position  int32
}

func (q *Queries) CreateObjective(ctx context.Context, arg CreateObjectiveParams) (CourseObjective, error) {
	row := q.db.QueryRow(ctx, createObjective,
		arg.ID,
		arg.CourseID,
		arg.Objective,
		arg.Position,
	)
	var i CourseObjective
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Objective,
		&i.Position,
	)
	return i, err
}

const createRequirement = `-- name: CreateRequirement :one
INSERT INTO course_requirements (id, course_id, requirement, position)
VALUES ($1, $2, $3, $4)
RETURNING id, course_id, requirement, position
`

type CreateRequirementParams struct {
	ID          pgtype.UUID
	CourseID    pgtype.UUID
	Requirement string
	Position    int32
}

func (q *Queries) CreateRequirement(ctx context.Context, arg CreateRequirementParams) (CourseRequirement, error) {
	row := q.db.QueryRow(ctx, createRequirement,
		arg.ID,
		arg.CourseID,
		arg.Requirement,
		arg.Position,
	)
	var i CourseRequirement
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Requirement,
		&i.Position,
	)
	return i, err
}

const createSection = `-- name: CreateSection :one
INSERT INTO sections (id, course_id, title, position)
VALUES ($1, $2, $3, $4)
RETURNING id, course_id, title, position
`

type CreateSectionParams struct {
	ID       pgtype.UUID
	CourseID pgtype.UUID
	Title    string
	Position int32
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, createSection,
		arg.ID,
		arg.CourseID,
		arg.Title,
		arg.Position,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Position,
	)
	return i, err
}

const createTarget = `-- name: CreateTarget :one
INSERT INTO course_targets (id, course_id, target, position)
VALUES ($1, $2, $3, $4)
RETURNING id, course_id, target, position
`

type CreateTargetParams struct {
	ID       pgtype.UUID
	CourseID pgtype.UUID
	Target   string
	Position int32
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (CourseTarget, error) {
	row := q.db.QueryRow(ctx, createTarget,
		arg.ID,
		arg.CourseID,
		arg.Target,
		arg.Position,
	)
	var i CourseTarget
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Target,
		&i.Position,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourse, id)
	return err
}

const deleteLesson = `-- name: DeleteLesson :exec
DELETE FROM lessons WHERE id = $1
`

func (q *Queries) DeleteLesson(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLesson, id)
	return err
}

const deleteLessonResource = `-- name: DeleteLessonResource :exec
DELETE FROM lesson_resources WHERE id = $1
`

func (q *Queries) DeleteLessonResource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLessonResource, id)
	return err
}

const deleteSection = `-- name: DeleteSection :exec
DELETE FROM sections WHERE id = $1
`

func (q *Queries) DeleteSection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSection, id)
	return err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name FROM categories WHERE name = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, owner_id, title, slug, subtitle, description, level, language, price, thumbnail_url, status, created_at, updated_at FROM courses WHERE id = $1
`

func (q *Queries) GetCourseByID(ctx context.Context, id pgtype.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Slug,
		&i.Subtitle,
		&i.Description,
		&i.Level,
		&i.Language,
		&i.Price,
		&i.ThumbnailUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, owner_id, title, slug, subtitle, description, level, language, price, thumbnail_url, status, created_at, updated_at FROM courses WHERE slug = $1
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Slug,
		&i.Subtitle,
		&i.Description,
		&i.Level,
		&i.Language,
		&i.Price,
		&i.ThumbnailUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT id, course_id, user_id, enrolled_at FROM enrollments WHERE course_id = $1 AND user_id = $2
`

type GetEnrollmentParams struct {
	CourseID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) GetEnrollment(ctx context.Context, arg GetEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollment, arg.CourseID, arg.UserID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.EnrolledAt,
	)
	return i, err
}

const getInboxEvent = `-- name: GetInboxEvent :one
SELECT event_id, processed_at FROM inbox_events WHERE event_id = $1
`

func (q *Queries) GetInboxEvent(ctx context.Context, eventID pgtype.UUID) (InboxEvent, error) {
	row := q.db.QueryRow(ctx, getInboxEvent, eventID)
	var i InboxEvent
	err := row.Scan(&i.EventID, &i.ProcessedAt)
	return i, err
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT id, section_id, title, type, duration, position FROM lessons WHERE id = $1
`

func (q *Queries) GetLessonByID(ctx context.Context, id pgtype.UUID) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLessonByID, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Title,
		&i.Type,
		&i.Duration,
		&i.Position,
	)
	return i, err
}

const getLessonOrder = `-- name: GetLessonOrder :one
SELECT section_id, ordered_ids FROM lesson_order WHERE section_id = $1
`

func (q *Queries) GetLessonOrder(ctx context.Context, sectionID pgtype.UUID) (LessonOrder, error) {
	row := q.db.QueryRow(ctx, getLessonOrder, sectionID)
	var i LessonOrder
	err := row.Scan(&i.SectionID, &i.OrderedIds)
	return i, err
}

const getSectionByID = `-- name: GetSectionByID :one
SELECT id, course_id, title, position FROM sections WHERE id = $1
`

func (q *Queries) GetSectionByID(ctx context.Context, id pgtype.UUID) (Section, error) {
	row := q.db.QueryRow(ctx, getSectionByID, id)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Position,
	)
	return i, err
}

const insertInboxEvent = `-- name: InsertInboxEvent :exec
INSERT INTO inbox_events (event_id, processed_at)
VALUES ($1, $2)
ON CONFLICT (event_id) DO NOTHING
`

type InsertInboxEventParams struct {
	EventID     pgtype.UUID
	ProcessedAt pgtype.Timestamp
}

func (q *Queries) InsertInboxEvent(ctx context.Context, arg InsertInboxEventParams) error {
	_, err := q.db.Exec(ctx, insertInboxEvent, arg.EventID, arg.ProcessedAt)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (id, aggregate_id, aggregate_type, event_type, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOutboxEventParams struct {
	ID            pgtype.UUID
	AggregateID   pgtype.UUID
	AggregateType pgtype.Text
	EventType     pgtype.Text
	Payload       []byte
	CreatedAt     pgtype.Timestamp
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.AggregateID,
		arg.AggregateType,
		arg.EventType,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name FROM categories ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByCourseID = `-- name: ListCategoriesByCourseID :many
SELECT c.id, c.name FROM categories c
JOIN course_categories cc ON c.id = cc.category_id
WHERE cc.course_id = $1
ORDER BY c.name ASC
`

func (q *Queries) ListCategoriesByCourseID(ctx context.Context, courseID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByCourseID, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, owner_id, title, slug, subtitle, description, level, language, price, thumbnail_url, status, created_at, updated_at FROM courses
ORDER BY created_at DESC
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Slug,
			&i.Subtitle,
			&i.Description,
			&i.Level,
			&i.Language,
			&i.Price,
			&i.ThumbnailUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesByOwner = `-- name: ListCoursesByOwner :many
SELECT id, owner_id, title, slug, subtitle, description, level, language, price, thumbnail_url, status, created_at, updated_at FROM courses
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCoursesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Slug,
			&i.Subtitle,
			&i.Description,
			&i.Level,
			&i.Language,
			&i.Price,
			&i.ThumbnailUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollmentsByUserID = `-- name: ListEnrollmentsByUserID :many
SELECT e.id, e.course_id, e.user_id, e.enrolled_at, c.title as course_title, c.slug as course_slug, c.thumbnail_url as course_thumbnail_url
FROM enrollments e
JOIN courses c ON e.course_id = c.id
WHERE e.user_id = $1
ORDER BY e.enrolled_at DESC
`

type ListEnrollmentsByUserIDRow struct {
	ID                 pgtype.UUID
	CourseID           pgtype.UUID
	UserID             pgtype.UUID
	EnrolledAt         pgtype.Timestamp
	CourseTitle        string
	CourseSlug         string
	CourseThumbnailUrl pgtype.Text
}

func (q *Queries) ListEnrollmentsByUserID(ctx context.Context, userID pgtype.UUID) ([]ListEnrollmentsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listEnrollmentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentsByUserIDRow
	for rows.Next() {
		var i ListEnrollmentsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.UserID,
			&i.EnrolledAt,
			&i.CourseTitle,
			&i.CourseSlug,
			&i.CourseThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsBySectionID = `-- name: ListLessonsBySectionID :many
SELECT id, section_id, title, type, duration, position FROM lessons WHERE section_id = $1 ORDER BY position ASC
`

func (q *Queries) ListLessonsBySectionID(ctx context.Context, sectionID pgtype.UUID) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessonsBySectionID, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Title,
			&i.Type,
			&i.Duration,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectivesByCourseID = `-- name: ListObjectivesByCourseID :many
SELECT id, course_id, objective, position FROM course_objectives WHERE course_id = $1 ORDER BY position ASC
`

func (q *Queries) ListObjectivesByCourseID(ctx context.Context, courseID pgtype.UUID) ([]CourseObjective, error) {
	rows, err := q.db.Query(ctx, listObjectivesByCourseID, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseObjective
	for rows.Next() {
		var i CourseObjective
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Objective,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCourses = `-- name: ListPublishedCourses :many
SELECT id, owner_id, title, slug, subtitle, description, level, language, price, thumbnail_url, status, created_at, updated_at FROM courses
WHERE status = 'PUBLISHED'
ORDER BY created_at DESC
`

func (q *Queries) ListPublishedCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listPublishedCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Slug,
			&i.Subtitle,
			&i.Description,
			&i.Level,
			&i.Language,
			&i.Price,
			&i.ThumbnailUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirementsByCourseID = `-- name: ListRequirementsByCourseID :many
SELECT id, course_id, requirement, position FROM course_requirements WHERE course_id = $1 ORDER BY position ASC
`

func (q *Queries) ListRequirementsByCourseID(ctx context.Context, courseID pgtype.UUID) ([]CourseRequirement, error) {
	rows, err := q.db.Query(ctx, listRequirementsByCourseID, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseRequirement
	for rows.Next() {
		var i CourseRequirement
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Requirement,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByLessonID = `-- name: ListResourcesByLessonID :many
SELECT id, lesson_id, title, url, type, created_at FROM lesson_resources WHERE lesson_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListResourcesByLessonID(ctx context.Context, lessonID pgtype.UUID) ([]LessonResource, error) {
	rows, err := q.db.Query(ctx, listResourcesByLessonID, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonResource
	for rows.Next() {
		var i LessonResource
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Title,
			&i.Url,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByCourseID = `-- name: ListSectionsByCourseID :many
SELECT id, course_id, title, position FROM sections WHERE course_id = $1 ORDER BY position ASC
`

func (q *Queries) ListSectionsByCourseID(ctx context.Context, courseID pgtype.UUID) ([]Section, error) {
	rows, err := q.db.Query(ctx, listSectionsByCourseID, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetsByCourseID = `-- name: ListTargetsByCourseID :many
SELECT id, course_id, target, position FROM course_targets WHERE course_id = $1 ORDER BY position ASC
`

func (q *Queries) ListTargetsByCourseID(ctx context.Context, courseID pgtype.UUID) ([]CourseTarget, error) {
	rows, err := q.db.Query(ctx, listTargetsByCourseID, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseTarget
	for rows.Next() {
		var i CourseTarget
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Target,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedOutboxEvents = `-- name: ListUnpublishedOutboxEvents :many
SELECT id, aggregate_id, aggregate_type, event_type, payload, created_at, published_at FROM outbox_events
WHERE published_at IS NULL
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventAsPublished = `-- name: MarkOutboxEventAsPublished :exec
UPDATE outbox_events
SET published_at = $2
WHERE id = $1
`

type MarkOutboxEventAsPublishedParams struct {
	ID          pgtype.UUID
	PublishedAt pgtype.Timestamp
}

func (q *Queries) MarkOutboxEventAsPublished(ctx context.Context, arg MarkOutboxEventAsPublishedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventAsPublished, arg.ID, arg.PublishedAt)
	return err
}

const setLessonOrder = `-- name: SetLessonOrder :one
INSERT INTO lesson_order (section_id, ordered_ids)
VALUES ($1, $2)
ON CONFLICT (section_id) DO UPDATE SET ordered_ids = EXCLUDED.ordered_ids
RETURNING section_id, ordered_ids
`

type SetLessonOrderParams struct {
	SectionID  pgtype.UUID
	OrderedIds []pgtype.UUID
}

func (q *Queries) SetLessonOrder(ctx context.Context, arg SetLessonOrderParams) (LessonOrder, error) {
	row := q.db.QueryRow(ctx, setLessonOrder, arg.SectionID, arg.OrderedIds)
	var i LessonOrder
	err := row.Scan(&i.SectionID, &i.OrderedIds)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET title = $2, slug = $3, subtitle = $4, description = $5, level = $6, language = $7, price = $8, thumbnail_url = $9, status = $10, updated_at = $11
WHERE id = $1
RETURNING id, owner_id, title, slug, subtitle, description, level, language, price, thumbnail_url, status, created_at, updated_at
`

type UpdateCourseParams struct {
	ID           pgtype.UUID
	Title        string
	Slug         string
	Subtitle     pgtype.Text
	Description  pgtype.Text
	Level        pgtype.Text
	Language     pgtype.Text
	Price        pgtype.Numeric
	ThumbnailUrl pgtype.Text
	Status       string
	UpdatedAt    pgtype.Timestamp
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Subtitle,
		arg.Description,
		arg.Level,
		arg.Language,
		arg.Price,
		arg.ThumbnailUrl,
		arg.Status,
		arg.UpdatedAt,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Slug,
		&i.Subtitle,
		&i.Description,
		&i.Level,
		&i.Language,
		&i.Price,
		&i.ThumbnailUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLesson = `-- name: UpdateLesson :one
UPDATE lessons
SET title = $2, type = $3, duration = $4, position = $5
WHERE id = $1
RETURNING id, section_id, title, type, duration, position
`

type UpdateLessonParams struct {
	ID       pgtype.UUID
	Title    string
	Type     string
	Duration pgtype.Int4
	Position pgtype.Int4
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, updateLesson,
		arg.ID,
		arg.Title,
		arg.Type,
		arg.Duration,
		arg.Position,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Title,
		&i.Type,
		&i.Duration,
		&i.Position,
	)
	return i, err
}

const updateSection = `-- name: UpdateSection :one
UPDATE sections
SET title = $2, position = $3
WHERE id = $1
RETURNING id, course_id, title, position
`

type UpdateSectionParams struct {
	ID       pgtype.UUID
	Title    string
	Position int32
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, updateSection, arg.ID, arg.Title, arg.Position)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Position,
	)
	return i, err
}
