apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

helmCharts:
  - name: api
    releaseName: api-dev
    version: 0.1.0
    repo: ../../charts
    valuesInline:
      replicaCount: 1
      ingress:
        hosts:
          - host: api-dev.chaindeploy.dev
            paths:
              - path: /
                pathType: Prefix
      env:
        DATABASE_URL: "postgresql://postgres:postgres@postgres-dev-postgresql:5432/chaindeploy"
        REDIS_URL: "redis://redis-dev-master:6379"
      autoscaling:
        enabled: false

  - name: frontend
    releaseName: frontend-dev
    version: 0.1.0
    repo: ../../charts
    valuesInline:
      replicaCount: 1
      ingress:
        hosts:
          - host: app-dev.chaindeploy.dev
            paths:
              - path: /
                pathType: Prefix

  - name: builder
    releaseName: builder-dev
    version: 0.1.0
    repo: ../../charts
    valuesInline:
      replicaCount: 1
      env:
        DATABASE_URL: "postgresql://postgres:postgres@postgres-dev-postgresql:5432/chaindeploy"
        REDIS_URL: "redis://redis-dev-master:6379"
      autoscaling:
        enabled: false

  - name: deployer
    releaseName: deployer-dev
    version: 0.1.0
    repo: ../../charts
    valuesInline:
      replicaCount: 1
      env:
        DATABASE_URL: "postgresql://postgres:postgres@postgres-dev-postgresql:5432/chaindeploy"
        REDIS_URL: "redis://redis-dev-master:6379"
      autoscaling:
        enabled: false

  - name: indexer
    releaseName: indexer-dev
    version: 0.1.0
    repo: ../../charts
    valuesInline:
      replicaCount: 1
      env:
        DATABASE_URL: "postgresql://postgres:postgres@postgres-dev-postgresql:5432/chaindeploy"
        REDIS_URL: "redis://redis-dev-master:6379"
      autoscaling:
        enabled: false
