namespace: url-shortener-dev

backend:
  replicaCount: 1
  image:
    repository: shaharyarshakir/url-shortener-backend
    tag: latest

frontend:
  replicaCount: 1
  image:
    repository: shaharyarshakir/url-shortener-frontend
    tag: latest

vault:
  enabled: false

ingress:
  enabled: false

postgres:
  storage: 5Gi
