server:
  port: 5000

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  jwt:
    issuer: identity-service
    access-token-expiration: 15m
    refresh-token-expiration: 30d
    private-key: classpath:keys/private.pem
    public-key: classpath:keys/public.pem
