[k8s_masters]
master-01 ansible_host=10.0.1.100 ansible_user=ubuntu

[k8s_workers]
worker-01 ansible_host=10.0.2.101 ansible_user=ubuntu
worker-02 ansible_host=10.0.2.102 ansible_user=ubuntu

[k8s_all:children]
k8s_masters
k8s_workers

[k8s_all:vars]
ansible_ssh_private_key_file=~/.ssh/resume-ai-key.pem
ansible_python_interpreter=/usr/bin/python3
