# Generated by Django 5.2.16 on 2026-07-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionORM',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('media_id', models.UUIDField(db_index=True)),
                ('language', models.TextField(max_length=10)),
                ('label', models.TextField(max_length=100)),
                ('format', models.TextField(max_length=10)),
                ('storage_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'captions',
                'indexes': [models.Index(fields=['media_id'], name='captions_media_i_78e70a_idx'), models.Index(fields=['language'], name='captions_languag_4b2fc9_idx')],
                'unique_together': {('media_id', 'language')},
            },
        ),
        migrations.CreateModel(
            name='VideoMetadataORM',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('media_id', models.UUIDField(db_index=True, unique=True)),
                ('duration', models.IntegerField(default=0)),
                ('master_playlist_key', models.TextField()),
                ('thumbnail_key', models.TextField(blank=True, null=True)),
                ('preview_sprite_key', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='PROCESSING')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'video_metadata',
                'indexes': [models.Index(fields=['media_id'], name='video_metad_media_i_cf007e_idx'), models.Index(fields=['status'], name='video_metad_status_1e84a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchProgressORM',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('lesson_id', models.UUIDField(db_index=True)),
                ('media_id', models.UUIDField(db_index=True)),
                ('position', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_played_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'watch_progress',
                'indexes': [models.Index(fields=['user_id', 'lesson_id'], name='watch_progr_user_id_9904b8_idx'), models.Index(fields=['media_id'], name='watch_progr_media_i_224e91_idx'), models.Index(fields=['completed'], name='watch_progr_complet_94b54d_idx')],
                'unique_together': {('user_id', 'lesson_id')},
            },
        ),
    ]
