apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

helmCharts:
  - name: api
    releaseName: api-staging
    version: 0.1.0
    repo: ../../charts
    valuesInline:
      replicaCount: 2
      ingress:
        hosts:
          - host: api-staging.chaindeploy.dev
            paths:
              - path: /
                pathType: Prefix
      env:
        DATABASE_URL: "postgresql://postgres:postgres@postgres-staging-postgresql:5432/chaindeploy"
        REDIS_URL: "redis://redis-staging-master:6379"
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 5

  - name: frontend
    releaseName: frontend-staging
    version: 0.1.0
    repo: ../../charts
    valuesInline:
      replicaCount: 2
      ingress:
        hosts:
          - host: app-staging.chaindeploy.dev
            paths:
              - path: /
                pathType: Prefix

  - name: builder
    releaseName: builder-staging
    version: 0.1.0
    repo: ../../charts
    valuesInline:
      replicaCount: 2
      env:
        DATABASE_URL: "postgresql://postgres:postgres@postgres-staging-postgresql:5432/chaindeploy"
        REDIS_URL: "redis://redis-staging-master:6379"
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3

  - name: deployer
    releaseName: deployer-staging
    version: 0.1.0
    repo: ../../charts
    valuesInline:
      replicaCount: 2
      env:
        DATABASE_URL: "postgresql://postgres:postgres@postgres-staging-postgresql:5432/chaindeploy"
        REDIS_URL: "redis://redis-staging-master:6379"
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3

  - name: indexer
    releaseName: indexer-staging
    version: 0.1.0
    repo: ../../charts
    valuesInline:
      replicaCount: 2
      env:
        DATABASE_URL: "postgresql://postgres:postgres@postgres-staging-postgresql:5432/chaindeploy"
        REDIS_URL: "redis://redis-staging-master:6379"
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
