apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: url-shortener-prod

resources:
  - ../../base
  - hpa.yaml

helmGlobals:
  chartHome: ../../../helm

helmCharts:
  - name: url-shortener
    releaseName: url-shortener
    version: 0.1.0
    includeCRDs: true
    valuesFile: values.yaml
