apiVersion: v1
kind: Secret
metadata:
  name: s3-secret-helm
  namespace: {{ .Values.namespace }}
  annotations:
    serving.kserve.io/s3-endpoint: {{ .Values.storage.s3Endpoint | quote }}
    serving.kserve.io/s3-usehttps: {{ .Values.storage.useHttps | quote }}
    serving.kserve.io/s3-verifyssl: {{ .Values.storage.verifySsl | quote }}
    serving.kserve.io/s3-region: {{ .Values.storage.region | quote }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.storage.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.secretAccessKey | quote }}
  AWS_DEFAULT_REGION: {{ .Values.storage.region | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-sa-helm
  namespace: {{ .Values.namespace }}
secrets:
  - name: s3-secret-helm
